---
title: "1.1 Getting started"
subtitle: "PLSC30500, Fall 2021"
# author: "Andy Eggers & Molly Offer-Westort"
output: 
  xaringan::moon_reader:
    css: [default, shinobi]
    nature:
      highlightStyle: atelier-lakeside-light
      highlightLines: true
      countIncrementalSlides: false
  
---


# Big picture: the research process vs research training 

1. **Data collection**: run survey, enter data from archive, etc
1. **Data processing (programming)**: merge, recode, reshape, aggregate, etc
1. **Data analysis**: visualization, model fitting, hypothesis testing, etc 

--

Compared to typical intro stats courses, we will do: 

- more on visualization
- more on programming 
- more using those tools to learn other concepts


???

Typical stats sequences basically deal with model fitting and hyp testing only. But you spend ~ 90% of time on 1 and 2, and visualization is very important. So we're redressing this somewhat.

---

# Our plan (overview)

- "Data science" first (weeks 1-2, every lab and homework)
  - visualization on "tidied" data
  - learn to "tidy" our data
- Probability/stats essentials (week 3)
- Research design essentials: causality and experiments (week 4)
- Regression (weeks 5 & 6) 
- Inference (weeks 7 & 8)

Cumulative -- please keep up.

???

Foregrounding "data science" skills, causality.

---

# Expectations about background

Some background in 

- programming
- probability & statistics
- econometrics/regression modeling

is useful, but not required.

--

If *lots* of this background, maybe you're in the wrong course!


---

# Programming in `R` 

Which one is you? 

1. Never done any programming
1. Did some programming in another language (e.g. Python, Stata)
1. Some experience programming in `R`
1. Experienced at programming in `R`

--

All welcome, but plan your work accordingly.

---

# Expectations for the course 

- Prepare for class
- Participate (ask and answer questions)

---

# Getting and giving help

You will get stuck.

1. Use google.
1. If you're still stuck, ask your question on our private StackOverflow (https://stackoverflow.com/c/uchicagopolmeth)
1. Or if you're brave, ask on the real StackOverflow (https://stackoverflow.com/) if it's about `R` or CrossValidated (https://stats.stackexchange.com/) if it's about stats. 

Please also *answer* questions on our private StackOverflow.

---

# Assessment 

- 60% problem sets
- 30% final 


# Useful resources 

- RStudio Cloud primers (online, interactive) 
- *R For Data Science* book (online or print)  
- Google
- StackOverflow: our private one and "real" one
- Lectures and labs

---

# Assignment for Thursday

Attempt primers 1.1 and 1.2 on RStudio Cloud: 

- "Data visualization basics" (https://rstudio.cloud/learn/primers/1.1)
- "Programming basics" (https://rstudio.cloud/learn/primers/1.2)

--

To note: 

- For beginners: these are not really sequential, so do 1.2 even if you are lost in 1.1
- For non-beginners: if these are too basic, work on "R For Data Science" (R4DS) (including exercises)
- For experienced R programmers: if R4DS too easy for you, let's talk


